/**
 * Secondary action, follow-through and overlap.
 *
 * Principle 5 as a mechanism rather than a hope: appendages lag the body by
 * two to six frames, and secondary channels keep moving during holds. The
 * animation validator measures exactly these two things, so they are
 * generated by the same rules they are judged against.
 */

import type { Channel, SecondaryChannel, Bone } from '../graph/types.ts';
import { offsetChannel, sampleChannel, evaluateChannel } from '../timing/curves.ts';
import { makeChannel } from '../timing/curves.ts';
import { correlation, derivative } from '../core/math.ts';

export type OverlapOptions = {
  /** Frames of lag. Must land inside the 2-6 window to pass validation. */
  lagFrames?: number;
  /** How much of the driver's motion the appendage inherits. */
  amplitude?: number;
};

/**
 * Derive an overlapping channel for an appendage from its driver.
 *
 * The appendage does not copy the driver: it lags it and overshoots
 * slightly, which is what "drag and follow-through" looks like in curves.
 */
export function deriveOverlap(
  driver: Channel,
  targetBone: string,
  options: OverlapOptions = {},
): Channel {
  const lag = Math.max(2, Math.min(6, Math.round(options.lagFrames ?? 3)));
  const amplitude = options.amplitude ?? 0.55;
  const shifted = offsetChannel(driver, lag);
  return {
    target: `bone:${targetBone}.rotation`,
    additive: true,
    keyframes: shifted.keyframes.map((k, i, all) => {
      const prev = all[i - 1];
      const delta = prev ? k.value - prev.value : 0;
      // Overshoot proportional to how fast the driver was moving.
      return {
        frame: k.frame,
        value: -(k.value * amplitude) - delta * amplitude * 0.6,
        ease: 'easeOut' as const,
      };
    }),
  };
}

/** Build overlap channels for every spring/appendage bone on a rig. */
export function buildOverlapChannels(
  bones: readonly Bone[],
  curves: readonly Channel[],
  options: OverlapOptions = {},
): { channels: Channel[]; declared: SecondaryChannel[] } {
  const channels: Channel[] = [];
  const declared: SecondaryChannel[] = [];
  const byTarget = new Map(curves.map((c) => [c.target, c]));

  for (const bone of bones) {
    if (!bone.spring || !bone.parent) continue;
    const driver = byTarget.get(`bone:${bone.parent}.rotation`);
    if (!driver || driver.keyframes.length < 2) continue;
    // Heavier appendages lag further behind.
    const lag = Math.max(2, Math.min(6, Math.round(2 + (bone.spring.mass / 0.5))));
    channels.push(deriveOverlap(driver, bone.id, { ...options, lagFrames: lag }));
    declared.push({
      target: `bone:${bone.id}.rotation`,
      lagFrames: lag,
      amplitude: options.amplitude ?? 0.55,
      source: 'spring',
    });
  }
  return { channels, declared };
}

/**
 * Measure the phase lag between two channels by cross-correlating their
 * velocity profiles. This is what the overlap validator reports.
 */
export function measureLag(
  driver: Channel,
  follower: Channel,
  start: number,
  end: number,
  maxLag = 12,
): { lagFrames: number; strength: number } {
  const a = derivative(sampleChannel(driver, start, end));
  const b = derivative(sampleChannel(follower, start, end));
  if (a.length < 4 || b.length < 4) return { lagFrames: 0, strength: 0 };
  let bestLag = 0;
  let best = -Infinity;
  for (let lag = 0; lag <= maxLag; lag++) {
    const x = a.slice(0, a.length - lag);
    const y = b.slice(lag);
    const c = Math.abs(correlation(x, y));
    if (c > best) {
      best = c;
      bestLag = lag;
    }
  }
  return { lagFrames: bestLag, strength: Number.isFinite(best) ? best : 0 };
}

/**
 * Secondary action during a hold.
 *
 * A hold where nothing at all moves is a dead frame. This adds a small,
 * slow drift to a secondary channel so the character stays alive without
 * the main pose changing.
 */
export function secondaryDuringHold(
  target: string,
  startFrame: number,
  endFrame: number,
  amplitude: number,
): Channel {
  const mid = Math.round((startFrame + endFrame) / 2);
  return makeChannel(
    target,
    [
      [startFrame, 0],
      [mid, amplitude],
      [endFrame, amplitude * 0.3],
    ],
    'easeInOut',
    true,
  );
}

/** Does anything move in this frame range? The "dead hold" detector. */
export function hasMotion(
  channels: readonly Channel[],
  start: number,
  end: number,
  threshold = 1e-4,
): boolean {
  for (const c of channels) {
    const a = evaluateChannel(c, start);
    for (let f = start + 1; f <= end; f++) {
      if (Math.abs(evaluateChannel(c, f) - a) > threshold) return true;
    }
  }
  return false;
}
