import { createImage, getPixel } from '../src/raster/buffer.ts';
import { fillContours, strokePolyline, rasterizeMask, coverageToMask } from '../src/raster/rasterize.ts';
import { encodePng, decodePng } from '../src/raster/png.ts';
import { blur, grade, vignette } from '../src/raster/filters.ts';
import { deltaERgb, parseHex } from '../src/core/color.ts';

const img = createImage(120, 90, { r: 250, g: 248, b: 240, a: 1 });
fillContours(img, [[{x:20,y:20},{x:100,y:25},{x:90,y:70},{x:25,y:65}]], { color: parseHex('#3a7ad9') });
strokePolyline(img, [{x:20,y:20},{x:100,y:25},{x:90,y:70},{x:25,y:65}], { color: {r:20,g:20,b:30}, width: 3, join:'round' }, true);
const png = encodePng(img);
const back = decodePng(png);
let maxDiff = 0;
for (let i=0;i<img.data.length;i++) maxDiff = Math.max(maxDiff, Math.abs(img.data[i]-back.data[i]));
console.log('png bytes', png.length, 'roundtrip maxDiff', maxDiff);
console.log('center px', getPixel(img, 60, 45));
const m = coverageToMask(rasterizeMask([[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}]], 20, 20));
let n=0; for (const v of m) n+=v;
console.log('mask area (expect 100):', n);
const g = grade(img, { lift: 0.02, gamma: 1.1, gain: 1.05, saturation: 1.2 });
const b = blur(g, 2); const v = vignette(b, 0.3, 0.6);
console.log('filters ok', v.width, v.height);
console.log('deltaE identical:', deltaERgb({r:58,g:122,b:217},{r:58,g:122,b:217}).toFixed(4));
console.log('deltaE near:', deltaERgb({r:58,g:122,b:217},{r:60,g:125,b:220}).toFixed(3));
